### ISSUE TITLE
Support for 4.25.4

### ISSUE THREAD

**Issue by dangerstudios** [sideeffects/HoudiniLiveLink#2]
Would it be possible to compile for the latest version of unreal?

4.24.**4**

At the moment it only supports; 4.24.**3**

**Comment by OptimisticMonkey** [comment]
Closing this: Works in 4.26 and 5.0. See releases section for binary downloads.

**Comment by dangerstudios** [comment]
Would it be possible to compile for the latest version of unreal, 4.27?
