### ISSUE TITLE
Support for 4.26

### ISSUE THREAD

**Issue by dangerstudios** [sideeffects/HoudiniLiveLink#3]
Any support of anything other than 4.25.3?

4.24.x
4.25.x
4.26.x

ect

**Comment by shamotina** [comment]
Plus one

**Comment by OptimisticMonkey** [comment]
Would love if this worked with 4.26

**Comment by OptimisticMonkey** [comment]
Closing this:  Works in 4.26 and 5.0.  See releases section for binary downloads.
