### ISSUE TITLE
Support for 5.0.0

### ISSUE THREAD

**Issue by eldiren** [sideeffects/HoudiniLiveLink#6]
The final 5.0.0 version was released on April 5th,2022. Can we get a release for that version.

**Comment by OptimisticMonkey** [comment]
Uploaded new binaries for 5.0.3 on releases tab: [https://github.com/sideeffects/HoudiniLiveLink/releases/download/v1.1/HoudiniLiveLinkv1.2-UE5.0.3.zip](5.0.3https://github.com/sideeffects/HoudiniLiveLink/releases/download/v1.1/HoudiniLiveLinkv1.2-UE5.0.3.zip)

**Comment by OptimisticMonkey** [comment]
closing issue
